---
language: ruby
rvm:
  - 2.0.0
script: bundle exec rake spec
env:
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
  - |
    PUPPET_VERSION="~> 4.8.1"
    STRICT_VARIABLES=no
notifications:
  email:
    - sre@procore.com
